spring:
  application:
    name: mh-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mh_db
    username: meta
    password: secret1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect