services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mh_db'
      - 'POSTGRES_PASSWORD=secret1'
      - 'POSTGRES_USER=meta'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
